name: RequireOa
version: '${project.version}'
main: com.craftmend.openaudiomc.addons.requieoa.RequireOpenAudioAddon
api-version: 1.17
depend: [ OpenAudioMc ]
authors: [ Mindgamesnl ]
description: A simple plugin blocking player interaction, and kicking players if they don't connect to the audio client in time.
